(add-dm-fct '((872 isa image-data text "872" type image)
(872-json isa inc-label idata 872 label l-json)
(l-json isa label-data text "json")
(872-- isa inc-label idata 872 label l--)
(l-- isa label-data text "-")
(872-xls isa inc-label idata 872 label l-xls)
(l-xls isa label-data text "xls")
(872-com isa inc-label idata 872 label l-com)
(l-com isa label-data text "com")
(872-- isa inc-label idata 872 label l--)
(l-- isa label-data text "-")
(872-json isa inc-label idata 872 label l-json)
(l-json isa label-data text "json")
(872-/ isa inc-label idata 872 label l-/)
(l-/ isa label-data text "/")
(872-xml isa inc-label idata 872 label l-xml)
(l-xml isa label-data text "xml")
(872-to isa inc-label idata 872 label l-to)
(l-to isa label-data text "to")
(872-excel isa inc-label idata 872 label l-excel)
(l-excel isa label-data text "excel")
(872-/ isa inc-label idata 872 label l-/)
(l-/ isa label-data text "/")
(872-CSV isa inc-label idata 872 label l-CSV)
(l-CSV isa label-data text "CSV")
(872-/ isa inc-label idata 872 label l-/)
(l-/ isa label-data text "/")
(872-html isa inc-label idata 872 label l-html)
(l-html isa label-data text "html")
(872-online isa inc-label idata 872 label l-online)
(l-online isa label-data text "online")
(872-converter isa inc-label idata 872 label l-converter)
(l-converter isa label-data text "converter")
(872-and isa inc-label idata 872 label l-and)
(l-and isa label-data text "and")
(872-viewer isa inc-label idata 872 label l-viewer)
(l-viewer isa label-data text "viewer")
(872-time4 isa time-data idata 872 time time4)
))